name: CI

env:
  SKIP_INSTALL_SIMPLE_GIT_HOOKS: 1

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Typecheck
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint
      - name: Tests
        run: pnpm run test
